window.BENCHMARK_DATA = {
  "lastUpdate": 1763023242989,
  "repoUrl": "https://github.com/GoogleChromeLabs/chromium-bidi",
  "entries": {
    "Benchmark": [
      {
        "commit": {
          "author": {
            "email": "69349599+sadym-chromium@users.noreply.github.com",
            "name": "Maksim Sadym",
            "username": "sadym-chromium"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "6f321e470e1c09fb9e76501b512fffa9579f55c2",
          "message": "chore: publish performance data to gh-pages (#3907)\n\n* Use `benchmark-action/github-action-benchmark@v1` to automate perf\nmetric storage and deployment.\n* Switch repo's GitHub Pages to deployment from branch `gh-pages`.\nRequired, as now there are 2 sources of information for gh-pages (WPT +\nperformance).\n* Update WPT report to override `wpt/index.html` and\n`wpt/wptreport-2023.html` in `gh-pages` branch.\n* Add `index.html` with links to the perf metrics and to the WPT reports\nthe root of `gh-pages` branch.\n* Example perf page: https://googlechromelabs.github.io/chromium-bidi/bench/index.html",
          "timestamp": "2025-11-12T11:51:40+01:00",
          "tree_id": "5a4b10876769f1243ce6f58636ff03633a086cc6",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/6f321e470e1c09fb9e76501b512fffa9579f55c2"
        },
        "date": 1762944820291,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 165.2696132659912,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1697.815179824829,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 1773.7640380859375,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3422.404956817627,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.86343002319336,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 234.27166938781738,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 204.82916831970215,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.76476669311523,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 284.848690032959,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b2b27389f42deacad6d80a7804fbad09bdb62283",
          "message": "build(chrome): update the pinned browser version to 144.0.7523.0 (#3906)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.\n\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>",
          "timestamp": "2025-11-12T11:16:11Z",
          "tree_id": "ee47860dc757bfc83637b6fd2c3b802aa7a83cc8",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b2b27389f42deacad6d80a7804fbad09bdb62283"
        },
        "date": 1762946355832,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 170.97444534301758,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3320.427179336548,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2608.496570587158,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 292.03052520751953,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 266.9369697570801,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2947.7521896362305,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 312.34517097473145,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 192.08884239196777,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 286.5670680999756,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 151.77078247070312,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "49699333+dependabot[bot]@users.noreply.github.com",
            "name": "dependabot[bot]",
            "username": "dependabot[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b0dd472c0de4ad5dcf0e61b25b5bf5559d2b28fc",
          "message": "chore(deps): Bump wpt from `8ac56ca` to `92639a9` (#3909)\n\nBumps [wpt](https://github.com/web-platform-tests/wpt) from `8ac56ca` to\n`92639a9`.\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/92639a9a19ea98347a4cb8d52def72570bb27dbc\"><code>92639a9</code></a>\nMap various tests to web-features (05) (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55585\">#55585</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/01af3c61ec65333413f20268bddd795a41e813e7\"><code>01af3c6</code></a>\nMake computed borders not affect the computed value.</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/a42b9f0fb3146b092b3dc20eeb7bdab03cb69ce4\"><code>a42b9f0</code></a>\n[css-values] Reduce viewport units when scrollbars are\nunconditional</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/c1794aaf2954aac447396b32a1c109106c2a8be1\"><code>c1794aa</code></a>\nMake test compliant with earlier test</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/e1b47f0a266517689629f966d8a61ae0a16f340b\"><code>e1b47f0</code></a>\n[wdspec] Add checks for overriding &quot;Accept-Language&quot; header\nwith &quot;emulation.s...</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/da5fad35a4948323e4e57db650e9acfaa06b842b\"><code>da5fad3</code></a>\nMap various tests to web-features (04) (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55481\">#55481</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/0fcc2ec326e516455f15d0a3f0b85146455db538\"><code>0fcc2ec</code></a>\n[Navigation API] Add test for navigation.entries() main frame excluding\nifram...</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/9f8490256485e4e9a2729e2896c8ce0336932916\"><code>9f84902</code></a>\nRespect overscroll-behavior when determining scroll bubbling (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55981\">#55981</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/7fd0c65f58856012a4cc63c28234ee6d6b93e8d0\"><code>7fd0c65</code></a>\nOptimize gfx::Transform's mojo.</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/6a0c261485ded794cdf1240c7092457db99b7e40\"><code>6a0c261</code></a>\nRevert &quot;Bug 1848958 - [wdspec] Update tests for dispatching mouse\nevents via ...</li>\n<li>Additional commits viewable in <a\nhref=\"https://github.com/web-platform-tests/wpt/compare/8ac56ca5bff0294794dfaaef0a9c3ee5b2da2d1b...92639a9a19ea98347a4cb8d52def72570bb27dbc\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\n\nDependabot will resolve any conflicts with this PR as long as you don't\nalter it yourself. You can also trigger a rebase manually by commenting\n`@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits\nthat have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after\nyour CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge\nand block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating\nit. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all\nof the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop\nDependabot creating any more for this major version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop\nDependabot creating any more for this minor version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop\nDependabot creating any more for this dependency (unless you reopen the\nPR or upgrade to it yourself)\n\n\n</details>\n\n---------\n\nSigned-off-by: dependabot[bot] <support@github.com>\nSigned-off-by: Browser Automation Bot <browser-automation-bot@google.com>\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>\nCo-authored-by: Browser Automation Bot <browser-automation-bot@google.com>",
          "timestamp": "2025-11-12T11:27:37Z",
          "tree_id": "93bcd3491b917daa96b7c1610fcd5893374ede19",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b0dd472c0de4ad5dcf0e61b25b5bf5559d2b28fc"
        },
        "date": 1762946981645,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 167.45381355285645,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1799.814224243164,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3356.698751449585,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 285.9618663787842,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 261.20896339416504,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2104.2928218841553,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 293.27917098999023,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.368896484375,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 282.5596332550049,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 168.36910247802734,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "69349599+sadym-chromium@users.noreply.github.com",
            "name": "Maksim Sadym",
            "username": "sadym-chromium"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b5521d7c93de57f660daf0da66ba3c902bc6473e",
          "message": "chore: link to perf in README.md (#3911)\n\nAdd link to the perf metrics to readme",
          "timestamp": "2025-11-12T12:38:00Z",
          "tree_id": "1ef09b3771fe2526516cb4af743c735fd49579de",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b5521d7c93de57f660daf0da66ba3c902bc6473e"
        },
        "date": 1762951198788,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 171.56758308410645,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3269.2633628845215,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 282.7589988708496,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 213.1403923034668,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2722.410821914673,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 229.6299934387207,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 168.2816982269287,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 291.89438819885254,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 178.02252769470215,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "9ad4a13067cb8eeb08c58caee7a7d3513a67827d",
          "message": "build(chrome): update the pinned browser version to 144.0.7524.0 (#3910)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-13T09:29:51+01:00",
          "tree_id": "4b5fe683b64f3c1bb138aa52ac7d8c31e9b5f545",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/9ad4a13067cb8eeb08c58caee7a7d3513a67827d"
        },
        "date": 1763022685307,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 178.23901176452637,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2999.8501777648926,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 1952.9719829559326,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 1767.1847820281982,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.3010005950928,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 278.629207611084,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 3235.6409549713135,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 245.48134803771973,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 185.66102981567383,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 282.70201683044434,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "49699333+dependabot[bot]@users.noreply.github.com",
            "name": "dependabot[bot]",
            "username": "dependabot[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "df5bec46f03ba75d050c58af322bd0d82bc944dd",
          "message": "chore(deps): Bump wpt from `92639a9` to `6a6e90a` (#3912)\n\nBumps [wpt](https://github.com/web-platform-tests/wpt) from `92639a9` to\n`6a6e90a`.\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/6a6e90a2df4c71d7592d67e2a417a9a7a7ee09a0\"><code>6a6e90a</code></a>\nUndo web-features mapping for CSS Typed OM overlapping test (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55989\">#55989</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/c498c7f6347671efddbc842d98c994f8899bc847\"><code>c498c7f</code></a>\nTranslator API: TranslateStreaming() Web Platform Tests</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/c450942caca0d0c67f23acd86917353de79abf67\"><code>c450942</code></a>\n[Gap Decorations]: Implement Paint logic for empty cells</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/b70ea7252a52acfedb81ae66e6f9327ce875211c\"><code>b70ea72</code></a>\n[webaudio-testharness] Migrate\naudioworkletnode-channel-count.https.html</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/875b9bea90a1c433ec6e14bb94445fec2119184b\"><code>875b9be</code></a>\nAdd WPTs for CookieStore subscribe() with optional or empty\narguments</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/e6ba136b87cdbabb117809c1f53d8c1eb9e6aeb0\"><code>e6ba136</code></a>\nWebKit export of <a\nhref=\"https://bugs.webkit.org/show_bug.cgi?id=302330\">https://bugs.webkit.org/show_bug.cgi?id=302330</a>\n(<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55991\">#55991</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/08a408bd3261093c01105b23bde6e70a20f922b1\"><code>08a408b</code></a>\nWait a full frame for the scroll timeline to become inactive</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/d702e50d6999b5ac1fdd815992887be83e49cbd7\"><code>d702e50</code></a>\nMake scroll-timeline snapshotting tests align with spec and\nproposal</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/62d2ddbeed017970d0d1f215a8b986f67916cbfc\"><code>62d2ddb</code></a>\nMake scroll-animation-effect-fill-modes.tentative.html pass</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/e03ae2228757e82f919a3f01ef2d639d58b59d36\"><code>e03ae22</code></a>\nAdd test for 'perspective(0.5px)' in 'transform' (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55998\">#55998</a>)</li>\n<li>Additional commits viewable in <a\nhref=\"https://github.com/web-platform-tests/wpt/compare/92639a9a19ea98347a4cb8d52def72570bb27dbc...6a6e90a2df4c71d7592d67e2a417a9a7a7ee09a0\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\n\nDependabot will resolve any conflicts with this PR as long as you don't\nalter it yourself. You can also trigger a rebase manually by commenting\n`@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits\nthat have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after\nyour CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge\nand block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating\nit. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all\nof the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop\nDependabot creating any more for this major version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop\nDependabot creating any more for this minor version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop\nDependabot creating any more for this dependency (unless you reopen the\nPR or upgrade to it yourself)\n\n\n</details>\n\nSigned-off-by: dependabot[bot] <support@github.com>\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>",
          "timestamp": "2025-11-13T08:37:48Z",
          "tree_id": "4b785b884380d6dda3495c91afbaa7285a85828d",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/df5bec46f03ba75d050c58af322bd0d82bc944dd"
        },
        "date": 1763023242453,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 174.63979721069336,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3699.539375305176,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 3687.53080368042,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2087.4576091766357,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.9090156555176,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 276.9681930541992,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2675.0091552734375,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 269.4643974304199,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 191.52345657348633,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 290.18144607543945,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 181.80904388427734,
            "unit": "ms"
          }
        ]
      }
    ]
  }
}