window.BENCHMARK_DATA = {
  "lastUpdate": 1764409190905,
  "repoUrl": "https://github.com/GoogleChromeLabs/chromium-bidi",
  "entries": {
    "Benchmark": [
      {
        "commit": {
          "author": {
            "email": "69349599+sadym-chromium@users.noreply.github.com",
            "name": "Maksim Sadym",
            "username": "sadym-chromium"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "6f321e470e1c09fb9e76501b512fffa9579f55c2",
          "message": "chore: publish performance data to gh-pages (#3907)\n\n* Use `benchmark-action/github-action-benchmark@v1` to automate perf\nmetric storage and deployment.\n* Switch repo's GitHub Pages to deployment from branch `gh-pages`.\nRequired, as now there are 2 sources of information for gh-pages (WPT +\nperformance).\n* Update WPT report to override `wpt/index.html` and\n`wpt/wptreport-2023.html` in `gh-pages` branch.\n* Add `index.html` with links to the perf metrics and to the WPT reports\nthe root of `gh-pages` branch.\n* Example perf page: https://googlechromelabs.github.io/chromium-bidi/bench/index.html",
          "timestamp": "2025-11-12T11:51:40+01:00",
          "tree_id": "5a4b10876769f1243ce6f58636ff03633a086cc6",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/6f321e470e1c09fb9e76501b512fffa9579f55c2"
        },
        "date": 1762944820291,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 165.2696132659912,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1697.815179824829,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 1773.7640380859375,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3422.404956817627,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.86343002319336,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 234.27166938781738,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 204.82916831970215,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.76476669311523,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 284.848690032959,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b2b27389f42deacad6d80a7804fbad09bdb62283",
          "message": "build(chrome): update the pinned browser version to 144.0.7523.0 (#3906)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.\n\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>",
          "timestamp": "2025-11-12T11:16:11Z",
          "tree_id": "ee47860dc757bfc83637b6fd2c3b802aa7a83cc8",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b2b27389f42deacad6d80a7804fbad09bdb62283"
        },
        "date": 1762946355832,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 170.97444534301758,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3320.427179336548,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2608.496570587158,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 292.03052520751953,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 266.9369697570801,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2947.7521896362305,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 312.34517097473145,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 192.08884239196777,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 286.5670680999756,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 151.77078247070312,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "49699333+dependabot[bot]@users.noreply.github.com",
            "name": "dependabot[bot]",
            "username": "dependabot[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b0dd472c0de4ad5dcf0e61b25b5bf5559d2b28fc",
          "message": "chore(deps): Bump wpt from `8ac56ca` to `92639a9` (#3909)\n\nBumps [wpt](https://github.com/web-platform-tests/wpt) from `8ac56ca` to\n`92639a9`.\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/92639a9a19ea98347a4cb8d52def72570bb27dbc\"><code>92639a9</code></a>\nMap various tests to web-features (05) (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55585\">#55585</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/01af3c61ec65333413f20268bddd795a41e813e7\"><code>01af3c6</code></a>\nMake computed borders not affect the computed value.</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/a42b9f0fb3146b092b3dc20eeb7bdab03cb69ce4\"><code>a42b9f0</code></a>\n[css-values] Reduce viewport units when scrollbars are\nunconditional</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/c1794aaf2954aac447396b32a1c109106c2a8be1\"><code>c1794aa</code></a>\nMake test compliant with earlier test</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/e1b47f0a266517689629f966d8a61ae0a16f340b\"><code>e1b47f0</code></a>\n[wdspec] Add checks for overriding &quot;Accept-Language&quot; header\nwith &quot;emulation.s...</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/da5fad35a4948323e4e57db650e9acfaa06b842b\"><code>da5fad3</code></a>\nMap various tests to web-features (04) (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55481\">#55481</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/0fcc2ec326e516455f15d0a3f0b85146455db538\"><code>0fcc2ec</code></a>\n[Navigation API] Add test for navigation.entries() main frame excluding\nifram...</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/9f8490256485e4e9a2729e2896c8ce0336932916\"><code>9f84902</code></a>\nRespect overscroll-behavior when determining scroll bubbling (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55981\">#55981</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/7fd0c65f58856012a4cc63c28234ee6d6b93e8d0\"><code>7fd0c65</code></a>\nOptimize gfx::Transform's mojo.</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/6a0c261485ded794cdf1240c7092457db99b7e40\"><code>6a0c261</code></a>\nRevert &quot;Bug 1848958 - [wdspec] Update tests for dispatching mouse\nevents via ...</li>\n<li>Additional commits viewable in <a\nhref=\"https://github.com/web-platform-tests/wpt/compare/8ac56ca5bff0294794dfaaef0a9c3ee5b2da2d1b...92639a9a19ea98347a4cb8d52def72570bb27dbc\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\n\nDependabot will resolve any conflicts with this PR as long as you don't\nalter it yourself. You can also trigger a rebase manually by commenting\n`@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits\nthat have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after\nyour CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge\nand block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating\nit. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all\nof the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop\nDependabot creating any more for this major version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop\nDependabot creating any more for this minor version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop\nDependabot creating any more for this dependency (unless you reopen the\nPR or upgrade to it yourself)\n\n\n</details>\n\n---------\n\nSigned-off-by: dependabot[bot] <support@github.com>\nSigned-off-by: Browser Automation Bot <browser-automation-bot@google.com>\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>\nCo-authored-by: Browser Automation Bot <browser-automation-bot@google.com>",
          "timestamp": "2025-11-12T11:27:37Z",
          "tree_id": "93bcd3491b917daa96b7c1610fcd5893374ede19",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b0dd472c0de4ad5dcf0e61b25b5bf5559d2b28fc"
        },
        "date": 1762946981645,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 167.45381355285645,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1799.814224243164,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3356.698751449585,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 285.9618663787842,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 261.20896339416504,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2104.2928218841553,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 293.27917098999023,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.368896484375,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 282.5596332550049,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 168.36910247802734,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "69349599+sadym-chromium@users.noreply.github.com",
            "name": "Maksim Sadym",
            "username": "sadym-chromium"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b5521d7c93de57f660daf0da66ba3c902bc6473e",
          "message": "chore: link to perf in README.md (#3911)\n\nAdd link to the perf metrics to readme",
          "timestamp": "2025-11-12T12:38:00Z",
          "tree_id": "1ef09b3771fe2526516cb4af743c735fd49579de",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b5521d7c93de57f660daf0da66ba3c902bc6473e"
        },
        "date": 1762951198788,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 171.56758308410645,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3269.2633628845215,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 282.7589988708496,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 213.1403923034668,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2722.410821914673,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 229.6299934387207,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 168.2816982269287,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 291.89438819885254,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 178.02252769470215,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "9ad4a13067cb8eeb08c58caee7a7d3513a67827d",
          "message": "build(chrome): update the pinned browser version to 144.0.7524.0 (#3910)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-13T09:29:51+01:00",
          "tree_id": "4b5fe683b64f3c1bb138aa52ac7d8c31e9b5f545",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/9ad4a13067cb8eeb08c58caee7a7d3513a67827d"
        },
        "date": 1763022685307,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 178.23901176452637,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2999.8501777648926,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 1952.9719829559326,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 1767.1847820281982,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.3010005950928,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 278.629207611084,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 3235.6409549713135,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 245.48134803771973,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 185.66102981567383,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 282.70201683044434,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "49699333+dependabot[bot]@users.noreply.github.com",
            "name": "dependabot[bot]",
            "username": "dependabot[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "df5bec46f03ba75d050c58af322bd0d82bc944dd",
          "message": "chore(deps): Bump wpt from `92639a9` to `6a6e90a` (#3912)\n\nBumps [wpt](https://github.com/web-platform-tests/wpt) from `92639a9` to\n`6a6e90a`.\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/6a6e90a2df4c71d7592d67e2a417a9a7a7ee09a0\"><code>6a6e90a</code></a>\nUndo web-features mapping for CSS Typed OM overlapping test (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55989\">#55989</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/c498c7f6347671efddbc842d98c994f8899bc847\"><code>c498c7f</code></a>\nTranslator API: TranslateStreaming() Web Platform Tests</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/c450942caca0d0c67f23acd86917353de79abf67\"><code>c450942</code></a>\n[Gap Decorations]: Implement Paint logic for empty cells</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/b70ea7252a52acfedb81ae66e6f9327ce875211c\"><code>b70ea72</code></a>\n[webaudio-testharness] Migrate\naudioworkletnode-channel-count.https.html</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/875b9bea90a1c433ec6e14bb94445fec2119184b\"><code>875b9be</code></a>\nAdd WPTs for CookieStore subscribe() with optional or empty\narguments</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/e6ba136b87cdbabb117809c1f53d8c1eb9e6aeb0\"><code>e6ba136</code></a>\nWebKit export of <a\nhref=\"https://bugs.webkit.org/show_bug.cgi?id=302330\">https://bugs.webkit.org/show_bug.cgi?id=302330</a>\n(<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55991\">#55991</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/08a408bd3261093c01105b23bde6e70a20f922b1\"><code>08a408b</code></a>\nWait a full frame for the scroll timeline to become inactive</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/d702e50d6999b5ac1fdd815992887be83e49cbd7\"><code>d702e50</code></a>\nMake scroll-timeline snapshotting tests align with spec and\nproposal</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/62d2ddbeed017970d0d1f215a8b986f67916cbfc\"><code>62d2ddb</code></a>\nMake scroll-animation-effect-fill-modes.tentative.html pass</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/e03ae2228757e82f919a3f01ef2d639d58b59d36\"><code>e03ae22</code></a>\nAdd test for 'perspective(0.5px)' in 'transform' (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55998\">#55998</a>)</li>\n<li>Additional commits viewable in <a\nhref=\"https://github.com/web-platform-tests/wpt/compare/92639a9a19ea98347a4cb8d52def72570bb27dbc...6a6e90a2df4c71d7592d67e2a417a9a7a7ee09a0\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\n\nDependabot will resolve any conflicts with this PR as long as you don't\nalter it yourself. You can also trigger a rebase manually by commenting\n`@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits\nthat have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after\nyour CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge\nand block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating\nit. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all\nof the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop\nDependabot creating any more for this major version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop\nDependabot creating any more for this minor version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop\nDependabot creating any more for this dependency (unless you reopen the\nPR or upgrade to it yourself)\n\n\n</details>\n\nSigned-off-by: dependabot[bot] <support@github.com>\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>",
          "timestamp": "2025-11-13T08:37:48Z",
          "tree_id": "4b785b884380d6dda3495c91afbaa7285a85828d",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/df5bec46f03ba75d050c58af322bd0d82bc944dd"
        },
        "date": 1763023242453,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 174.63979721069336,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3699.539375305176,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 3687.53080368042,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2087.4576091766357,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.9090156555176,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 276.9681930541992,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2675.0091552734375,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 269.4643974304199,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 191.52345657348633,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 290.18144607543945,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 181.80904388427734,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "8c2fdbab8768fcc2ea8299c3ac960888442ba0d6",
          "message": "build(chrome): update the pinned browser version to 144.0.7526.0 (#3913)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-13T16:32:32+01:00",
          "tree_id": "85b4182f8c30d7674198edfacb749ae796a73a43",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/8c2fdbab8768fcc2ea8299c3ac960888442ba0d6"
        },
        "date": 1763048131740,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 180.62233924865723,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1938.6272430419922,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2834.4077587127686,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3655.346155166626,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.0015468597412,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 251.93376541137695,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2147.966957092285,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 222.17082977294922,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 187.6750946044922,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 285.6250762939453,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "49699333+dependabot[bot]@users.noreply.github.com",
            "name": "dependabot[bot]",
            "username": "dependabot[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b0f5c26c78ba135f84aebe9495172467fe2f5870",
          "message": "chore(deps): Bump wpt from `6a6e90a` to `b5e7146` (#3914)\n\nBumps [wpt](https://github.com/web-platform-tests/wpt) from `6a6e90a` to\n`b5e7146`.\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/b5e7146b954154d4e2e02b8bd2362d74c2071e0e\"><code>b5e7146</code></a>\nWebKit export of <a\nhref=\"https://bugs.webkit.org/show_bug.cgi?id=256956\">https://bugs.webkit.org/show_bug.cgi?id=256956</a>\n(<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/56026\">#56026</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/8940f6bc954131ceebd59b82b102c99f4fbd6dd8\"><code>8940f6b</code></a>\nElements with required acc parent role with presentational role and\nglobal WA...</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/6827c6a75645b048ef37f3452b3f9e5bf08943e0\"><code>6827c6a</code></a>\nA couple of fixes for the CSS <code>random()</code> tests (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55867\">#55867</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/d63e0191c091f21293402e5af8a36bd98d97b910\"><code>d63e019</code></a>\nWebKit export of <a\nhref=\"https://bugs.webkit.org/show_bug.cgi?id=300093\">https://bugs.webkit.org/show_bug.cgi?id=300093</a>\n(<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/56023\">#56023</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/90347773f4f137ef43300f8e41a304cae8427132\"><code>9034777</code></a>\nWebKit export of <a\nhref=\"https://bugs.webkit.org/show_bug.cgi?id=294206\">https://bugs.webkit.org/show_bug.cgi?id=294206</a>\n(<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/56022\">#56022</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/221e9fcf17a526cd01c62fa45ef6277a5f93a507\"><code>221e9fc</code></a>\nSimplify assertions in navigation-api iframe history test (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/56020\">#56020</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/c3bb201215849adb80695dfe7fa8ef541cd179f2\"><code>c3bb201</code></a>\nAdd an infrastructure reftest for devicePixelRatio</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/1d940d73dc66c4632575933abe1e4ae8f10eb432\"><code>1d940d7</code></a>\nRevert &quot;Fix reference for anchor-scroll-position-try-012 due to\nmistaken cont...</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/f4e2abc22206d81772fc5cb9aad0a35921f2eac3\"><code>f4e2abc</code></a>\nDon't parse anchor functions in flex-basis. (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55971\">#55971</a>)</li>\n<li><a\nhref=\"https://github.com/web-platform-tests/wpt/commit/676bf0e691c1173ddbe454056048278cd63a0566\"><code>676bf0e</code></a>\nUpdate sanitizer-boolean-defaults to match current spec. (<a\nhref=\"https://redirect.github.com/web-platform-tests/wpt/issues/55959\">#55959</a>)</li>\n<li>Additional commits viewable in <a\nhref=\"https://github.com/web-platform-tests/wpt/compare/6a6e90a2df4c71d7592d67e2a417a9a7a7ee09a0...b5e7146b954154d4e2e02b8bd2362d74c2071e0e\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\n\nDependabot will resolve any conflicts with this PR as long as you don't\nalter it yourself. You can also trigger a rebase manually by commenting\n`@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits\nthat have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after\nyour CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge\nand block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating\nit. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all\nof the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop\nDependabot creating any more for this major version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop\nDependabot creating any more for this minor version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop\nDependabot creating any more for this dependency (unless you reopen the\nPR or upgrade to it yourself)\n\n\n</details>\n\nSigned-off-by: dependabot[bot] <support@github.com>\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
          "timestamp": "2025-11-14T09:29:48Z",
          "tree_id": "170d5650e32cb439249befecaec6b30cf305850f",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b0f5c26c78ba135f84aebe9495172467fe2f5870"
        },
        "date": 1763112684943,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 171.31404876708984,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2315.9722328186035,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2447.9100227355957,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2767.826986312866,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 285.3968620300293,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 296.66337966918945,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2438.211965560913,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 373.0233669281006,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 195.0096607208252,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 288.87696266174316,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "a45ee1b2e70cf7fd17cb6fd8c9c7d6253faf78d3",
          "message": "build(chrome): update the pinned browser version to 144.0.7526.3 (#3915)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-14T13:32:04+01:00",
          "tree_id": "01e7684c622437e3513f53b3290517e7de369ed6",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/a45ee1b2e70cf7fd17cb6fd8c9c7d6253faf78d3"
        },
        "date": 1763123654481,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 183.1261157989502,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2166.5413856506348,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 3229.047727584839,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2055.8807849884033,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 281.91566467285156,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 253.07521820068357,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2454.497814178467,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 347.96061515808105,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 188.63844871520996,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 285.7656478881836,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 178.0766487121582,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "OrKoN@users.noreply.github.com",
            "name": "Alex Rudenko",
            "username": "OrKoN"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "154abaaec7e35dc86bcc9dcfd9384d58a65cca08",
          "message": "fix: correctly report data sizes (#3836)\n\nCo-authored-by: Maksim Sadym <sadym@chromium.org>\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>",
          "timestamp": "2025-11-14T14:00:46+01:00",
          "tree_id": "96c777863da2f296fce154a70506b60c5ada0215",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/154abaaec7e35dc86bcc9dcfd9384d58a65cca08"
        },
        "date": 1763125408885,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 174.59421157836914,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2586.1398220062256,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2975.2789974212646,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2324.6342182159424,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 259.18378829956055,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 338.78560066223145,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 1914.6739482879639,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 339.9763584136963,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 191.50567054748535,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 282.6685428619385,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "b421d27106b1c42fcf6f910c0e7c68e7f47edf22",
          "message": "chore(main): release chromium-bidi 11.0.1 (#3916)\n\n:robot: I have created a release *beep* *boop*\n---\n\n\n##\n[11.0.1](https://github.com/GoogleChromeLabs/chromium-bidi/compare/chromium-bidi-v11.0.0...chromium-bidi-v11.0.1)\n(2025-11-14)\n\n\n### Bug Fixes\n\n* correctly report data sizes\n([#3836](https://github.com/GoogleChromeLabs/chromium-bidi/issues/3836))\n([154abaa](https://github.com/GoogleChromeLabs/chromium-bidi/commit/154abaaec7e35dc86bcc9dcfd9384d58a65cca08))\n\n---\nThis PR was generated with [Release\nPlease](https://github.com/googleapis/release-please). See\n[documentation](https://github.com/googleapis/release-please#release-please).",
          "timestamp": "2025-11-14T13:14:24Z",
          "tree_id": "21d2fac4977769866373c566ed46435d6cb4dacf",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/b421d27106b1c42fcf6f910c0e7c68e7f47edf22"
        },
        "date": 1763126199661,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 176.78685188293457,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1788.959789276123,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 1897.3616123199463,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2431.486749649048,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.6120891571045,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 334.95521545410156,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2635.2723598480225,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 239.77899551391602,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 194.17171478271484,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 278.14579010009766,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 171.3338851928711,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "49699333+dependabot[bot]@users.noreply.github.com",
            "name": "dependabot[bot]",
            "username": "dependabot[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "ee07939cb6c32644c7f3b68584b30f8f1dbae023",
          "message": "chore(deps-dev): Bump js-yaml from 4.1.0 to 4.1.1 (#3918)\n\nBumps [js-yaml](https://github.com/nodeca/js-yaml) from 4.1.0 to 4.1.1.\n<details>\n<summary>Changelog</summary>\n<p><em>Sourced from <a\nhref=\"https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md\">js-yaml's\nchangelog</a>.</em></p>\n<blockquote>\n<h2>[4.1.1] - 2025-11-12</h2>\n<h3>Security</h3>\n<ul>\n<li>Fix prototype pollution issue in yaml merge (&lt;&lt;)\noperator.</li>\n</ul>\n</blockquote>\n</details>\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/nodeca/js-yaml/commit/cc482e775913e6625137572a3712d2826170e53a\"><code>cc482e7</code></a>\n4.1.1 released</li>\n<li><a\nhref=\"https://github.com/nodeca/js-yaml/commit/50968b862e75866ef90e626572fe0b2f97b55f9f\"><code>50968b8</code></a>\ndist rebuild</li>\n<li><a\nhref=\"https://github.com/nodeca/js-yaml/commit/d092d866031751cb27c12d93f3e2470ad74d678b\"><code>d092d86</code></a>\nlint fix</li>\n<li><a\nhref=\"https://github.com/nodeca/js-yaml/commit/383665ff4248ec2192d1274e934462bb30426879\"><code>383665f</code></a>\nfix prototype pollution in merge (&lt;&lt;)</li>\n<li><a\nhref=\"https://github.com/nodeca/js-yaml/commit/0d3ca7a27b03a6c974790a30a89e456007d62976\"><code>0d3ca7a</code></a>\nREADME.md: HTTP =&gt; HTTPS (<a\nhref=\"https://redirect.github.com/nodeca/js-yaml/issues/678\">#678</a>)</li>\n<li><a\nhref=\"https://github.com/nodeca/js-yaml/commit/49baadd52af887d2991e2c39a6639baa56d6c71b\"><code>49baadd</code></a>\ndoc: 'empty' style option for !!null</li>\n<li><a\nhref=\"https://github.com/nodeca/js-yaml/commit/ba3460eb9d3e4478edcbc29edabe17c2157fc9ce\"><code>ba3460e</code></a>\nFix demo link (<a\nhref=\"https://redirect.github.com/nodeca/js-yaml/issues/618\">#618</a>)</li>\n<li>See full diff in <a\nhref=\"https://github.com/nodeca/js-yaml/compare/4.1.0...4.1.1\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\n\n[![Dependabot compatibility\nscore](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=js-yaml&package-manager=npm_and_yarn&previous-version=4.1.0&new-version=4.1.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)\n\nDependabot will resolve any conflicts with this PR as long as you don't\nalter it yourself. You can also trigger a rebase manually by commenting\n`@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits\nthat have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after\nyour CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge\nand block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating\nit. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all\nof the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop\nDependabot creating any more for this major version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop\nDependabot creating any more for this minor version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop\nDependabot creating any more for this dependency (unless you reopen the\nPR or upgrade to it yourself)\nYou can disable automated security fix PRs for this repo from the\n[Security Alerts\npage](https://github.com/GoogleChromeLabs/chromium-bidi/network/alerts).\n\n</details>\n\nSigned-off-by: dependabot[bot] <support@github.com>\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>",
          "timestamp": "2025-11-17T10:11:05+01:00",
          "tree_id": "532663da377e641c3b1bf792b2e43242d3e7285a",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/ee07939cb6c32644c7f3b68584b30f8f1dbae023"
        },
        "date": 1763370792422,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 177.9432773590088,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2128.180170059204,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 1911.6455554962158,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2614.3092155456543,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 265.2390956878662,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 252.10914611816403,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2858.966016769409,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 245.7047939300537,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 167.66858100891113,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 281.412935256958,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "1a9848ae3a821d5a45b4de22182c2d2a3bc4710a",
          "message": "build(chrome): update the pinned browser version to 144.0.7529.0 (#3917)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.\n\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>",
          "timestamp": "2025-11-17T09:18:58Z",
          "tree_id": "245cc949c14c694b3fa21c0aa6529c13849d985f",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/1a9848ae3a821d5a45b4de22182c2d2a3bc4710a"
        },
        "date": 1763371317722,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 141.32342338562012,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3162.7052307128906,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 3465.201425552368,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2519.982957839966,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 267.97070503234863,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 263.7998104095459,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2491.5595531463623,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 275.8538246154785,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.535551071167,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 272.68290519714355,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "cf6cca2634406dc3efec70bda7b555ae0ba0bb1d",
          "message": "build(chrome): update the pinned browser version to 144.0.7530.0 (#3919)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-18T10:27:28+01:00",
          "tree_id": "bead4b4bb01977aa414e68dc1ae38151c7dd178a",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/cf6cca2634406dc3efec70bda7b555ae0ba0bb1d"
        },
        "date": 1763458212777,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 165.06800651550293,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2511.8646144866943,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 3106.507968902588,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 3055.9897899627686,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 271.8057632446289,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 258.7007999420166,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 1999.1225719451904,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 267.33222007751465,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.6299171447754,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 281.30998611450195,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 171.4869499206543,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "a2bfd114e4a9f6230729c6766e98bdfb42e0378f",
          "message": "build(chrome): update the pinned browser version to 144.0.7531.0 (#3921)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-19T10:29:17+01:00",
          "tree_id": "1063b4d78bef1060c5f903dc3d5375f068db3f36",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/a2bfd114e4a9f6230729c6766e98bdfb42e0378f"
        },
        "date": 1763544670663,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 168.13325881958008,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3254.6053409576416,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 3435.2628231048584,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2013.4314060211182,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 268.65572929382324,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 243.79620552062988,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 3146.387767791748,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 357.80038833618164,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.17625427246094,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 278.45592498779297,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 169.39425468444824,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "49699333+dependabot[bot]@users.noreply.github.com",
            "name": "dependabot[bot]",
            "username": "dependabot[bot]"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "6acb1530b5ecfaa8a48d66f0569a12388986627c",
          "message": "chore(deps): Bump glob (#3920)\n\nBumps and [glob](https://github.com/isaacs/node-glob). These\ndependencies needed to be updated together.\nUpdates `glob` from 10.4.5 to 10.5.0\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/isaacs/node-glob/commit/56774ef73b495eb0b17cdd0f42921f5ef62297c1\"><code>56774ef</code></a>\n10.5.0</li>\n<li><a\nhref=\"https://github.com/isaacs/node-glob/commit/1e4e297342a09f2aa0ced87fcd4a70ddc325d75f\"><code>1e4e297</code></a>\nbin: Do not expose filenames to shell expansion</li>\n<li>See full diff in <a\nhref=\"https://github.com/isaacs/node-glob/compare/v10.4.5...v10.5.0\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\nUpdates `glob` from 11.0.3 to 11.1.0\n<details>\n<summary>Commits</summary>\n<ul>\n<li><a\nhref=\"https://github.com/isaacs/node-glob/commit/56774ef73b495eb0b17cdd0f42921f5ef62297c1\"><code>56774ef</code></a>\n10.5.0</li>\n<li><a\nhref=\"https://github.com/isaacs/node-glob/commit/1e4e297342a09f2aa0ced87fcd4a70ddc325d75f\"><code>1e4e297</code></a>\nbin: Do not expose filenames to shell expansion</li>\n<li>See full diff in <a\nhref=\"https://github.com/isaacs/node-glob/compare/v10.4.5...v10.5.0\">compare\nview</a></li>\n</ul>\n</details>\n<br />\n\n\nDependabot will resolve any conflicts with this PR as long as you don't\nalter it yourself. You can also trigger a rebase manually by commenting\n`@dependabot rebase`.\n\n[//]: # (dependabot-automerge-start)\n[//]: # (dependabot-automerge-end)\n\n---\n\n<details>\n<summary>Dependabot commands and options</summary>\n<br />\n\nYou can trigger Dependabot actions by commenting on this PR:\n- `@dependabot rebase` will rebase this PR\n- `@dependabot recreate` will recreate this PR, overwriting any edits\nthat have been made to it\n- `@dependabot merge` will merge this PR after your CI passes on it\n- `@dependabot squash and merge` will squash and merge this PR after\nyour CI passes on it\n- `@dependabot cancel merge` will cancel a previously requested merge\nand block automerging\n- `@dependabot reopen` will reopen this PR if it is closed\n- `@dependabot close` will close this PR and stop Dependabot recreating\nit. You can achieve the same result by closing it manually\n- `@dependabot show <dependency name> ignore conditions` will show all\nof the ignore conditions of the specified dependency\n- `@dependabot ignore this major version` will close this PR and stop\nDependabot creating any more for this major version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this minor version` will close this PR and stop\nDependabot creating any more for this minor version (unless you reopen\nthe PR or upgrade to it yourself)\n- `@dependabot ignore this dependency` will close this PR and stop\nDependabot creating any more for this dependency (unless you reopen the\nPR or upgrade to it yourself)\nYou can disable automated security fix PRs for this repo from the\n[Security Alerts\npage](https://github.com/GoogleChromeLabs/chromium-bidi/network/alerts).\n\n</details>\n\nSigned-off-by: dependabot[bot] <support@github.com>\nCo-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>\nCo-authored-by: Maksim Sadym <69349599+sadym-chromium@users.noreply.github.com>",
          "timestamp": "2025-11-19T09:39:12Z",
          "tree_id": "6250f56251b84b14693f0de635a3560a2f47f7ea",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/6acb1530b5ecfaa8a48d66f0569a12388986627c"
        },
        "date": 1763545322191,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 167.8732395172119,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3251.648235321045,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2629.833221435547,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 1854.5606136322021,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 271.43993377685547,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 342.316198348999,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 292.6002025604248,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.60969924926758,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 270.5618381500244,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 167.89789199829102,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "4f26b0cf56b9ae0aad731cd89d036b2ce9b8f88b",
          "message": "build(chrome): update the pinned browser version to 144.0.7533.2 (#3922)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-20T09:47:12+01:00",
          "tree_id": "4cf6e532d3312f4fb401b650807ec235d92a7566",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/4f26b0cf56b9ae0aad731cd89d036b2ce9b8f88b"
        },
        "date": 1763628599479,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 170.56550979614258,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 3380.8265686035156,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2669.113063812256,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 1897.9437828063965,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.3268451690674,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 344.8852062225342,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2849.1151809692383,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 217.45038032531738,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.89127159118652,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 279.21361923217773,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 170.7284450531006,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "a5ed6831dd73cd2cbfbed8b8ac42151ec9f1fe92",
          "message": "build(spec): update WebDriverBiDi types (#3923)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-bidi-types.yml\n\n---------\n\nCo-authored-by: Maksim Sadym <sadym@chromium.org>",
          "timestamp": "2025-11-21T10:37:57Z",
          "tree_id": "2988898bb998931a18694e11f58dc9f821213a7f",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/a5ed6831dd73cd2cbfbed8b8ac42151ec9f1fe92"
        },
        "date": 1763721615413,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 174.92575645446777,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1745.7727909088135,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 1716.3243770599365,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2181.7418098449707,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 278.41057777404785,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 251.63960456848145,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2663.292360305786,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 224.80478286743164,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 198.31476211547852,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 285.24022102355957,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "8bb5b36dc6eaf0591488620d9dde5c5f4815bc86",
          "message": "build(chrome): update the pinned browser version to 144.0.7543.0 (#3924)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-25T12:17:03Z",
          "tree_id": "324fde69a815908b40a48beb757a790ffbc18c92",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/8bb5b36dc6eaf0591488620d9dde5c5f4815bc86"
        },
        "date": 1764073148944,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 167.82712936401367,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 2341.3521766662598,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2691.1258220672607,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2325.0174045562744,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 274.3272304534912,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 222.67837524414062,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2776.9343852996826,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 316.2044048309326,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.16070938110352,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 267.5703525543213,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "133232582+browser-automation-bot@users.noreply.github.com",
            "name": "browser-automation-bot",
            "username": "browser-automation-bot"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "5d8a8fa20c34c836cb062559e2abae7cf9c5cce6",
          "message": "build(chrome): update the pinned browser version to 144.0.7548.0 (#3925)\n\nAutomatically generated by\nhttps://github.com/GoogleChromeLabs/chromium-bidi/blob/main/.github/workflows/update-browser-version.yml\n\nThis requires some manual work:\n1. Review and approve the PR.\n1. Approve and run workflows.\n1. Update WPT or e2e expectations and file issues if there was\nregression.\n1. Merge the PR.",
          "timestamp": "2025-11-28T11:59:06+01:00",
          "tree_id": "35dbe13889ba9d47ec9a05f49671fcf565615f5c",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/5d8a8fa20c34c836cb062559e2abae7cf9c5cce6"
        },
        "date": 1764327679138,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 167.50707626342773,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1970.3993797302246,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2238.288402557373,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2621.960401535034,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 275.1222610473633,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 326.75838470458984,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 2620.8346366882324,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 290.98639488220215,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 183.75749588012695,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 275.40717124938965,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 168.38536262512207,
            "unit": "ms"
          }
        ]
      },
      {
        "commit": {
          "author": {
            "email": "69349599+sadym-chromium@users.noreply.github.com",
            "name": "Maksim Sadym",
            "username": "sadym-chromium"
          },
          "committer": {
            "email": "noreply@github.com",
            "name": "GitHub",
            "username": "web-flow"
          },
          "distinct": true,
          "id": "4c030a44bcaff1fe5cb37ce78188c8fec1d9d067",
          "message": "ci: allow manual dispatch for puppeteer workflow (#3926)\n\nAllow for manual dispatch puppeteer CI workflow. Also run it on each\nmerge to main for keeping history.",
          "timestamp": "2025-11-29T10:38:16+01:00",
          "tree_id": "c523123cec1e72f9ffc9efd489b90350f4f77578",
          "url": "https://github.com/GoogleChromeLabs/chromium-bidi/commit/4c030a44bcaff1fe5cb37ce78188c8fec1d9d067"
        },
        "date": 1764409189459,
        "tool": "customSmallerIsBetter",
        "benches": [
          {
            "name": "ubuntu-latest-new-headless-node:test_performance_screenshot",
            "value": 168.28927993774414,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-cd:test_performance_screenshot",
            "value": 1880.8129787445068,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-node:test_performance_screenshot",
            "value": 2061.722421646118,
            "unit": "ms"
          },
          {
            "name": "macos-latest-headful-cd:test_performance_screenshot",
            "value": 2966.6746616363525,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-node:test_performance_screenshot",
            "value": 268.19214820861816,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-cd:test_performance_screenshot",
            "value": 222.58782386779785,
            "unit": "ms"
          },
          {
            "name": "macos-latest-new-headless-node:test_performance_screenshot",
            "value": 3444.2989349365234,
            "unit": "ms"
          },
          {
            "name": "macos-latest-old-headless-node:test_performance_screenshot",
            "value": 216.3626194000244,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-new-headless-cd:test_performance_screenshot",
            "value": 184.1966152191162,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-old-headless-cd:test_performance_screenshot",
            "value": 279.7476291656494,
            "unit": "ms"
          },
          {
            "name": "ubuntu-latest-headful-node:test_performance_screenshot",
            "value": 169.67215538024902,
            "unit": "ms"
          }
        ]
      }
    ]
  }
}