name: Pre-commit

# Declare default permissions as read only.
permissions: read-all

on:
  merge_group:
  pull_request:
  push:
    branches: 'main'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: '3.11'
      - name: Install ruff
        run: pip install ruff
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v5.0.0
      - name: Install keep-sorted
        run: |
          go install github.com/google/keep-sorted@v0.8.0
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Sync dependencies
        run: bash tools/gclient-sync.sh
      - name: Generate Ninja config
        run: npm run gn:gen
      - run: npm run build
      - name: Test that BidiMapper can be imported
        run: ./tools/node.py out/Default/gen/src/bidiMapper/BidiMapper.js
      - name: Run formatting and linting
        run: npm run format
      - name: Verify that codebase is fully formatted
        run: git diff --exit-code
