name: Publish

# Declare default permissions as read only.
permissions: read-all

env:
  FORCE_COLOR: 3
  PIP_DISABLE_PIP_VERSION_CHECK: 1

on:
  push:
    tags:
      - '*v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          cache: npm
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
      - name: Sync dependencies
        run: bash tools/gclient-sync.sh
      - name: Generate Ninja config
        run: npm run gn:gen
      - name: Build npm dependencies
        run: npm run build
      - name: Publish
        run: |
          npm publish --provenance --access public
