# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit tests

# Declare default permissions as read only.
permissions: read-all

env:
  FORCE_COLOR: 3

on:
  merge_group:
  pull_request:
  push:
    branches: 'main'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: Sync dependencies
        run: bash tools/gclient-sync.sh
      - name: Generate Ninja config
        run: npm run gn:gen
      - name: Build npm dependencies
        run: npm run build
      - name: Verify mapper size
        run: du -sh out/Default/gen/src/mapperTab.js
      - name: Run unit tests
        run: npm run unit
